// ex-vue/vue-cheatsheet.vue
// Vue Cheat Sheet

// Basic Setup (Vue 3)
<div id="app">{{ message }}</div>

<script src="https://unpkg.com/vue@3"></script>
<script>
const app = Vue.createApp({
  data() {
    return { message: 'Hello Vue!' }
  }
});
app.mount('#app');
</script>

// Template Syntax
<p>{{ message }}</p>

// Components

// Define a Component
const MyComponent = {
  template: `<div>Hello, {{ name }}!</div>`,
  props: ['name']
};

// Register Component
const app = Vue.createApp({});
app.component('my-component', MyComponent);
app.mount('#app');

// Props
// Usage example:
// <my-component name="Vue"></my-component>

// Reactive Data
data() {
  return {
    count: 0
  };
}

// Methods
methods: {
  increment() {
    this.count++;
  }
}

// Event Handling
<button @click="increment">Increment</button>

// Computed Properties
computed: {
  doubled() {
    return this.count * 2;
  }
}

// Watchers
watch: {
  count(newVal, oldVal) {
    console.log(`Count changed from ${oldVal} to ${newVal}`);
  }
}

// Conditional Rendering
<p v-if="isVisible">Visible!</p>
<p v-else>Hidden!</p>

// Lists Rendering
<ul>
  <li v-for="item in items" :key="item.id">{{ item.name }}</li>
</ul>

// Two-Way Binding
<input v-model="name" />

// Lifecycle Hooks
mounted() {
  console.log('Component mounted');
}

// Vue Router (Basic example)
import { createRouter, createWebHistory } from 'vue-router';

const routes = [
  { path: '/', component: Home },
  { path: '/about', component: About }
];

const router = createRouter({
  history: createWebHistory(),
  routes,
});

const app = Vue.createApp(App);
app.use(router);
app.mount('#app');

// ex-react/react-cheatsheet.js
// React Cheat Sheet

// Basic Setup
import React from 'react';
import ReactDOM from 'react-dom/client';

const App = () => <h1>Hello, React!</h1>;

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);

// JSX Syntax
const element = <h1 className="title">Hello, JSX!</h1>;

// Components

// Functional Component
function Welcome(props) {
  return <h1>Hello, {props.name}</h1>;
}

// Arrow Function Component
const WelcomeArrow = ({ name }) => <h1>Hello, {name}</h1>;

// Props
const Greeting = ({ message }) => <p>{message}</p>;

// Usage example
// <Greeting message="Welcome to React!" />

// State (using Hooks)
import React, { useState } from 'react';

function Counter() {
  const [count, setCount] = useState(0);

  return (
    <>
      <p>Count: {count}</p>
      <button onClick={() => setCount(count + 1)}>Increment</button>
    </>
  );
}

// Effect Hook (Side Effects)
import React, { useEffect } from 'react';

useEffect(() => {
  console.log('Component mounted or updated');

  return () => {
    console.log('Cleanup before next effect or unmount');
  };
}, [dependencies]); // empty array means run once on mount

// Event Handling
<button onClick={() => alert('Clicked!')}>Click me</button>;

// Conditional Rendering
{isLoggedIn ? <LogoutButton /> : <LoginButton />}

// Lists and Keys
const listItems = items.map(item => <li key={item.id}>{item.name}</li>);

// Forms
function NameForm() {
  const [name, setName] = useState('');

  return (
    <form>
      <input value={name} onChange={e => setName(e.target.value)} />
    </form>
  );
}

// Context API
const ThemeContext = React.createContext('light');

function AppWithContext() {
  return (
    <ThemeContext.Provider value="dark">
      <Toolbar />
    </ThemeContext.Provider>
  );
}

function Toolbar() {
  return <ThemedButton />;
}

function ThemedButton() {
  const theme = React.useContext(ThemeContext);
  return <button className={theme}>Button</button>;
}

// React Router (Basic example)
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';

function AppRouter() {
  return (
    <BrowserRouter>
      <nav>
        <Link to="/">Home</Link> | <Link to="/about">About</Link>
      </nav>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/about" element={<About />} />
      </Routes>
    </BrowserRouter>
  );
}
